services:
  mosquitto:
    image: ${MOSQUITTO_IMAGE:-eclipse-mosquitto:latest}
    container_name: mosquitto
    restart: always
    ports:
      - "${MOSQUITTO_PORT:-1883}:1883"
    networks:
      - ai_stack_net
    volumes:
      - /opt/tigerai/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"

  docling:
    image: ${DOCLING_IMAGE:-ghcr.io/docling-project/docling-serve-cpu:latest}
    container_name: docling-serve
    restart: always
    ports:
      # - "${HTTP_DOCLING_PORT:-5001}:5000"
      - "${HTTP_DOCLING_PORT:-5001}:5001"
    networks:
      - ai_stack_net
    shm_size: ${SHM_SIZE_RAG:-16gb}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - TZ=${TZ:-Asia/Taipei}
      - DOCLING_SERVE_MAX_SYNC_WAIT=9000
      - DOCLING_SERVE_ENABLE_UI=true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"

  qdrant:
    image: ${QDRANT_IMAGE:-qdrant/qdrant:latest}
    container_name: qdrant
    restart: always
    ports:
      - "${QDRANT_PORT:-6333}:6333"
      - "6334:6334"
    networks:
      - ai_stack_net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__STORAGE__PERFORMANCE__MAX_SEARCH_THREADS=40
      - QDRANT__STORAGE__PERFORMANCE__OPTIMIZER_MAX_THREADS=4
      - QDRANT__GPU__INDEXING=1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"

networks:
  ai_stack_net:
    external: true

volumes:
  qdrant_storage:
  mosquitto_data:
  mosquitto_log:
