services:
  redis:
    image: ${REDIS_IMAGE:-redis/redis-stack-server:latest}
    container_name: redis
    restart: always
    networks:
      - ai_stack_net
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"

  ollama:
    image: ${OLLAMA_IMAGE:-ollama/ollama:latest}
    container_name: ollama
    restart: always
    ports:
      - "${OLLAMA_PORT:-11434}:11434"
    networks:
      - ai_stack_net
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    volumes:
      - /var/lib/ollama:/root/.ollama
    environment:
      - OLLAMA_FLASH_ATTENTION=${OLLAMA_FLASH_ATTENTION:-1}
      - OLLAMA_NUM_PARALLEL=${OLLAMA_NUM_PARALLEL:-2}
      - OLLAMA_MAX_LOADED_MODELS=${OLLAMA_MAX_LOADED_MODELS:-2}
      - OLLAMA_KEEP_ALIVE=-1
      - OLLAMA_VULKAN=1
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"

  openwebui-main:
    image: ${OWUI_IMAGE:-ghcr.io/open-webui/open-webui:main}
    container_name: openwebui-main
    restart: unless-stopped
    ports:
      - "${OWUI_PORT:-8080}:8080"
    networks:
      - ai_stack_net
    shm_size: ${SHM_SIZE:-4gb}
    environment:
      - OPEN_WEBUI_MODE=queue
      - REDIS_URL=redis://redis:6379/1
      - DATABASE_URL=postgresql://${PG_USER:-adm}:${PG_PASS:-CHANGE_ME}@${PG_HOST:-postgres}:5432/${PG_DB_NAME:-tigerai}?options=-csearch_path=${OWUI_SCHEMA:-openwebui}
      - OLLAMA_API_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=${OWUI_SECRET_KEY:-CHANGE_ME}
      - OPENWEBUI_ROLE=web
      - WORKERS=${GUNICORN_WORKERS:-4}
      - AIOHTTP_CLIENT_TIMEOUT=${AIOHTTP_TIMEOUT:-900}
      - GUNICORN_TIMEOUT=${AIOHTTP_TIMEOUT:-900}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
      - ollama
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"

  openwebui-worker:
    image: ${OWUI_IMAGE:-ghcr.io/open-webui/open-webui:main}
    # container_name: openwebui-worker-01  <- 移除這一行才能 Scale
    restart: unless-stopped
    networks:
      - ai_stack_net
    shm_size: ${SHM_SIZE:-4gb}
    environment:
      - OPEN_WEBUI_MODE=queue
      - REDIS_URL=redis://redis:6379/1
      - DATABASE_URL=postgresql://${PG_USER:-adm}:${PG_PASS:-CHANGE_ME}@${PG_HOST:-postgres}:5432/${PG_DB_NAME:-tigerai}?options=-csearch_path=${OWUI_SCHEMA:-openwebui}
      - OLLAMA_API_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=${OWUI_SECRET_KEY:-CHANGE_ME}
      - OPENWEBUI_ROLE=worker
      - AIOHTTP_CLIENT_TIMEOUT=${AIOHTTP_TIMEOUT:-900}
      - GUNICORN_TIMEOUT=${AIOHTTP_TIMEOUT:-900}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
      - ollama
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"

networks:
  ai_stack_net:
    external: true
